[abc]
git-tree-sha1 = "2fde6d24ce7bffccc0a66a5447787bd95a057cca"

    [[abc.download]]
    sha256 = "a52485c26d1c239f97921a1b726faad5f0e642470a592234bdca2334c9892b7c"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/binaries/generic/abc.tar.gz"

[enzymes]
git-tree-sha1 = "df53cf90725e109caefe33fcb4e74ce64d509d78"

    [[enzymes.download]]
    sha256 = "72b4e3eceb02fe32c61bdace195da7e09d1a78ce8f9034876052adea44e5183a"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/enzymes.tar.gz"

[libras]
git-tree-sha1 = "5c13bb56bcf0d6866d26c80fde16b27e6ad2e75f"

    [[libras.download]]
    sha256 = "f67eda8a327217b18c9c22a19abc6f8a60e188107b0474c7836951edab41e407"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/libras.tar.gz"

[natops]
git-tree-sha1 = "3838ff4af3c2cf45a1cb6369a6138329f6362dcc"

    [[natops.download]]
    sha256 = "73e17a9f699a8222ffe4307c7d56674f71e5fd232ab75a855fd4e4901bc63bf5"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/natops.tar.gz"

[mitespresso]
git-tree-sha1 = "dbe79220f8352a25e5a79cdc3ede3c58abf9038f"

    [[mitespresso.download]]
    sha256 = "1b7655f5dc98f8484a6ec1fa709e03af16536cc98fc82a09eab1cb325d8234d5"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/binaries/minimizers/mitespresso.tar.gz"

[epilepsy]
git-tree-sha1 = "d4a858762ece9feb48b15831b93069f638ac610a"

    [[epilepsy.download]]
    sha256 = "d40fb45e1f1ecb696036c57602a87aa45a0f42e2e35baaccc8e4a1f301f74dbe"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/epilepsy.tar.gz"

[hugadb]
git-tree-sha1 = "a59cc61429942aa77b0d6a0bc2ffcf6f47acf7e0"

    [[hugadb.download]]
    sha256 = "e34ccf94cb1830cfda0c3007fbdb8a8810bcdde3e0219a12815fecff61798541"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/hugadb.tar.gz"

[paviauni]
git-tree-sha1 = "81396e68a00447706e3578371c010ca1e324037c"

    [[paviauni.download]]
    sha256 = "6c85460493385829630c275cdfa658c7eaf7a6c9618f95438137db55d533fcad"
    url = "https://github.com/aclai-lab/Artifacts/raw/main/sole/datasets/paviauni.tar.gz"
